# Generated by Django 3.1.7 on 2023-10-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Enter Card Number', max_length=16)),
                ('expiration_date', models.DateField(help_text='Expiration Date')),
                ('cvv', models.CharField(help_text='CVV/CVC', max_length=3)),
                ('card_holder_name', models.CharField(help_text='Card Holder Name', max_length=100)),
            ],
        ),
    ]
