# Generated by Django 3.1.7 on 2023-10-03 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentmod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('card_number', models.CharField(help_text='Enter Card Number', max_length=16)),
                ('expiration_date', models.DateField(help_text='Expiration Date')),
                ('cvv', models.CharField(help_text='CVV/CVC', max_length=3)),
                ('card_holder_name', models.CharField(help_text='Card Holder Name', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
