# Generated by Django 4.2.5 on 2023-10-04 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20231003_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentmod_upi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('upi_id', models.CharField(help_text='Enter UPI ID', max_length=30)),
                ('password', models.CharField(blank=True, help_text='Password/Pin (for Internet Banking or Wallet)', max_length=50, null=True)),
            ],
        ),
    ]
