# Generated by Django 3.1.7 on 2023-10-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_newletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentmod_upi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(help_text='Enter UPI ID', max_length=30)),
                ('password', models.CharField(blank=True, help_text='Password/Pin (for Internet Banking or Wallet)', max_length=50, null=True)),
            ],
        ),
    ]
