# Generated by Django 4.2.5 on 2023-10-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_paymentmod_upi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentmod_upi',
            name='transaction_id',
        ),
    ]
