# Generated by Django 3.1.7 on 2023-10-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_contact_users_remove_paymentmod_upi_transaction_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_users',
        ),
    ]
