# Generated by Django 4.2.6 on 2023-10-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_paymentmod_upi'),
        ('store', '0006_delete_contact_users'),
    ]

    operations = [
    ]
